namespace SharpGit2.Managed.Tests;

public sealed class WildMatchTests
{
    private const int CaseFoldFlag = (int)WildMatch.Flags.CaseFold;
    private const int PathNameFlag = (int)WildMatch.Flags.PathName;

    [Theory]
    [MemberData(nameof(TestCases))]
    public void WildMatchTheory(string pattern, string input, int flags, bool shouldMatch)
    {
        Assert.Equal(shouldMatch, WildMatch.Match(pattern, input, (WildMatch.Flags)flags) == WildMatch.Result.Match);

        if (!pattern.Contains('/') && !input.Contains('/'))
        {
            Assert.Equal(shouldMatch, WildMatch.Match(pattern, input, (WildMatch.Flags)flags | WildMatch.Flags.PathName) == WildMatch.Result.Match);
        }
    }

    public static TheoryData<string, string, int, bool> TestCases { get; } = new()
    {
        { "foo", "foo", 0, true },
        { "foo", "FOO", 0, false },
        { "foo", "FOO", CaseFoldFlag, true },
        { "@foo", "@foo", 0, true },
        { "@foo", "foo", 0, false },
        { "bar", "foo", 0, false },
        { "???", "foo", 0, true },
        { "??", "foo", 0, false },
        { "????", "foo", 0, false },
        { "*", "foo", 0, true },
        { "f*", "foo", 0, true },
        { "*f", "foo", 0, false },
        { "*foo*", "foo", 0, true },
        { "*ob*a*r*", "foobar", 0, true },
        { "*ab", "aaaaaaabababab", 0, true },
        { "foo\\*", "foo*", 0, true },
        { "foo\\*bar", "foobar", 0, false },
        { "f\\\\oo", "f\\oo", 0, true },
        { "*[al]?", "ball", 0, true },
        { "[ten]", "ten", 0, false },
        { "**[!te]", "ten", 0, true },
        { "**[!ten]", "ten", 0, false },
        { "t[a-g]n", "ten", 0, true },
        { "t[!a-g]n", "ten", 0, false },
        { "t[!a-g]n", "ton", 0, true },
        { "t[^a-g]n", "ton", 0, true },
        { "]", "]", 0, true },
        { "foo*bar", "foo/baz/bar", 0, true },
        { "foo*bar", "foo/baz/bar", PathNameFlag, false },
        { "foo?bar", "foo/bar", 0, true },
        { "foo?bar", "foo/bar", PathNameFlag, false },
        { "foo[/]bar", "foo/bar", 0, true },
        { "foo[/]bar", "foo/bar", PathNameFlag, false },
        { "f[^eiu][^eiu][^eiu][^eiu][^eiu]r", "foo/bar", 0, true },
        { "f[^eiu][^eiu][^eiu][^eiu][^eiu]r", "foo/bar", PathNameFlag, false },
        { "f[^eiu][^eiu][^eiu][^eiu][^eiu]r", "foo-bar", 0, true },
        { "**/foo", "foo", 0, false },
        { "**/foo", "foo", PathNameFlag, true },
        { "**/foo", "/foo", 0, true },
        { "**/foo", "/foo", PathNameFlag, true },
        { "**/foo", "bar/baz/foo", 0, true },
        { "**/foo", "bar/baz/foo", PathNameFlag, true },
        { "*/foo", "bar/baz/foo", 0, true },
        { "*/foo", "bar/baz/foo", PathNameFlag, false },
        { "**/bar*", "foo/bar/baz", 0, true },
        { "**/bar*", "foo/bar/baz", PathNameFlag, false },
        { "**/bar/*", "foo/bar/baz", 0, true },
        { "**/bar/*", "foo/bar/baz", PathNameFlag , true },
        { "**/bar/*", "deep/foo/bar/baz", 0, true },
        { "**/bar/*", "deep/foo/bar/baz", PathNameFlag, true },
        { "**/bar/*", "deep/foo/bar/baz/", 0, true },
        { "**/bar/*", "deep/foo/bar/baz/", PathNameFlag, true },
        { "**/bar/**", "deep/foo/bar/baz", 0, true },
        { "**/bar/**", "deep/foo/bar/baz", PathNameFlag, true },
        { "**/bar/**", "deep/foo/bar/baz/", 0, true },
        { "**/bar/**", "deep/foo/bar/baz/", PathNameFlag, true },
        { "**/bar/*", "deep/foo/bar", 0, false },
        { "**/bar/*", "deep/foo/bar", PathNameFlag, false },
        { "**/bar/**", "deep/foo/bar", 0, false },
        { "**/bar/**", "deep/foo/bar", PathNameFlag, false },
        { "**/bar/**", "deep/foo/bar/", 0, true },
        { "**/bar/**", "deep/foo/bar/", PathNameFlag, true },
        { "**/bar/**/*", "deep/foo/bar", 0, false },
        { "**/bar/**/*", "deep/foo/bar", PathNameFlag, false },
        { "**/bar/**/*", "deep/bar/bar", 0, false },
        { "**/bar/**/*", "deep/bar/bar", PathNameFlag, true },
        { "*/bar/**", "foo/bar/baz/x", 0, true },
        { "*/bar/**", "foo/bar/baz/x", PathNameFlag, true },
        { "*/bar/**", "deep/foo/bar/baz/x", 0, true },
        { "*/bar/**", "deep/foo/bar/baz/x", PathNameFlag, false },
        { "**/bar/*/*", "deep/foo/bar/baz/x", 0, true },
        { "**/bar/*/*", "deep/foo/bar/baz/x", PathNameFlag, true },
        { "*.txt", "foo/bar/baz.txt", 0, true },
        { "*.txt", "foo/bar/baz.txt", PathNameFlag, false },
        { "*.txt", "你好-世界.txt", 0, true },
        { "你好-世界.txt", "你好-世界.txt", 0, true },
        { "foo*", "foobar", 0, true },
        { "*foo*", "somethingfoobar", 0, true },
        { "*foo", "barfoo", 0, true },
        { "a[c-c]st", "acrt", 0, false },
        { "a[c-c]rt", "acrt", 0, true },
        { "\\", "''", 0, false },
        { "\\", "\\", 0, false },
        { "*/\\", "/\\", 0, false },
        { "\\[ab]", "[ab]", 0, true },
        { "[[]ab]", "[ab]", 0, true },
        { "[[:]ab]", "[ab]", 0, true },
        { "[[::]ab]", "[ab]", 0, true },
        { "[[:digit]ab]", "[ab]", 0, true },
        { "[\\[:]ab]", "[ab]", 0, true },
        { "\\??\\?b", "?a?b", 0, true },
        { "''", "foo", 0, false },
        { "**/t[o]", "foo/bar/baz/to", 0, true },
        { "**/t[o]", "foo/bar/baz/to", PathNameFlag, true },
        { "[[:alpha:]][[:digit:]][[:upper:]]", "a1B", 0, true },
        { "[[:digit:][:upper:][:space:]]", "a", 0, false },
        { "[[:digit:][:upper:][:space:]]", "A", 0, true },
        { "[[:digit:][:upper:][:space:]]", "1", 0, true },
        { "[[:digit:][:upper:][:spaci:]]", "1", 0, false },
        { "'", "'", 0, true },
        { "[[:digit:][:upper:][:space:]]", ".", 0, false },
        { "[[:digit:][:punct:][:space:]]", ".", 0, true },
        { "[[:xdigit:]]", "5", 0, true },
        { "[[:xdigit:]]", "f", 0, true },
        { "[[:xdigit:]]", "D", 0, true },
        { "[[:alnum:][:alpha:][:blank:][:cntrl:][:digit:][:graph:][:lower:][:print:][:punct:][:space:][:upper:][:xdigit:]]", "_", 0, true },
        { "[^[:alnum:][:alpha:][:blank:][:cntrl:][:digit:][:lower:][:space:][:upper:][:xdigit:]]", ".", 0, true },
        { "[a-c[:digit:]x-z]", "5", 0, true },
        { "[a-c[:digit:]x-z]", "b", 0, true },
        { "[a-c[:digit:]x-z]", "y", 0, true },
        { "[a-c[:digit:]x-z]", "q", 0, false },
        { "[\\\\-^]", "]", 0, true },
        { "[\\\\-^]", "[", 0, false },
        { "a[]b", "ab", 0, true },
        { "a[]b", "a[]b", 0, false },
        { "[!", "ab", 0, false },
        { "[-", "ab", 0, false },
        { "[-]", "-", 0, true },
        { "[a-", "-", 0, false },
        { "[!a-", "-", 0, false },
        { "'[", "0", 0, false },
        { "[---]", "-", 0, true },
        { "[------]", "-", 0, true },
        { "[!------]", "a", 0, true },
        { "[a^bc]", "^", 0, true },
        { "[\\]", "\\", 0, false },
        { "[\\\\]", "\\", 0, true },
        { "[!\\\\]", "\\", 0, false },
        { "[A-\\\\]", "G", 0, true },
        { "b*a", "aaabbb", 0, false },
        { "*ba*", "aabcaa", 0, false },
        { "[,]", ",", 0, true },
        { "[\\\\,]", ",", 0, true },
        { "[\\\\,]", "\\", 0, true },
        { "[,-.]", "-", 0, true },
        { "[,-.]", "+", 0, false },
        { "[,-.]", "-.]", 0, false },
        { "-*-*-*-*-*-*-12-*-*-*-m-*-*-*", "-adobe-courier-bold-o-normal--12-120-75-75-m-70-iso8859-1", 0, true },
        { "-*-*-*-*-*-*-12-*-*-*-m-*-*-*", "-adobe-courier-bold-o-normal--12-120-75-75-X-70-iso8859-1", 0, false },
        { "-*-*-*-*-*-*-12-*-*-*-m-*-*-*", "-adobe-courier-bold-o-normal--12-120-75-75-/-70-iso8859-1", 0, false },
        { "**/*a*b*g*n*t", "abcd/abcdefg/abcdefghijk/abcdefghijklmnop.txt", 0, true },
        { "**/*a*b*g*n*t", "abcd/abcdefg/abcdefghijk/abcdefghijklmnop.txt", PathNameFlag, true },
        { "**/*a*b*g*n*t", "abcd/abcdefg/abcdefghijk/abcdefghijklmnop.txtz", 0, false },
        { "**/*a*b*g*n*t", "abcd/abcdefg/abcdefghijk/abcdefghijklmnop.txtz", PathNameFlag, false },
        { "file[[:space:]]with[[:space:]]spaces.\\#", "file with spaces.#", 0, true },
        { "**/a*.txt", "foo-a.txt", 0, false },
        { "path/to/*.txt", "path/to/file.txt", 0, true },
        { "path/", "path/to/some/intermediaries/to/file.txt", 0, false },
        { "**/pdfkit.frameworks/pdfkit/**", "MyFolder/libs/pdfkit.frameworks/pdfkit", 0, false },
        { "**/pdfkit.frameworks/pdfkit/**", "MyFolder/libs/pdfkit.frameworks/pdfkit", PathNameFlag, false },
    };

}
